/**
 * Where generated bytes live — the OG card today, album PDFs and photos later.
 *
 * Declared here and implemented in `src/adapters/storage/`, the same dependency
 * inversion the payment provider and the SMS sender use (CLAUDE.md rules 6 and
 * 10). **No provider has been chosen.** Architecture §3 says S3-compatible in
 * `af-south-1`, and §15 item 6 has not decided between AWS Cape Town and Azure
 * Johannesburg, so the implementation that exists today writes to a local
 * directory and the S3 one arrives with that decision — one adapter, no change
 * anywhere else.
 *
 * The interface is deliberately smaller than any provider's API: get, put, has.
 * Nothing here deletes, because everything stored so far is content-addressed —
 * a key names bytes that cannot change, so the only reason to remove one is
 * housekeeping, which is an operational job rather than an application call.
 */

/**
 * An opaque key, `og/<event-id>/<version>.png` in the one caller there is.
 *
 * Slashes are a naming convention rather than a directory tree: S3 has no
 * directories, and an implementation that needs them can make them.
 */
export type ObjectKey = string

export interface StoredObject {
  readonly bytes: Uint8Array
  readonly contentType: string
}

export interface ObjectStore {
  get(key: ObjectKey): Promise<StoredObject | null>
  put(key: ObjectKey, object: StoredObject): Promise<void>
  has(key: ObjectKey): Promise<boolean>
}

/**
 * Keys are checked before they reach a filesystem or a bucket.
 *
 * The one caller builds keys from an event id and a hash, neither of which a
 * contributor controls — but a key that reached the local store with `..` in it
 * would write outside the cache directory, and "the caller is careful" is not a
 * property that survives a second caller.
 */
const VALID_KEY = /^[a-zA-Z0-9][a-zA-Z0-9._/-]*$/

export function isValidObjectKey(key: string): boolean {
  if (key.length === 0 || key.length > 512) return false
  if (key.includes('..') || key.includes('//')) return false

  return VALID_KEY.test(key)
}

export class ObjectStoreError extends Error {
  override readonly name = 'ObjectStoreError'
}
